trigger: none

extends:
  template: ../../eng/pipelines/templates/archetype-tests.yml
  parameters:
    Jobs:
    - template: jobs/archetype-sdk-tests.yml
      parameters:
        ServiceDirectory: identity
        EnvVars:
          AZURE_IDENTITY_TEST_TENANTID: $(net-identity-tenantid)
          AZURE_IDENTITY_TEST_USERNAME: $(net-identity-username)
          AZURE_IDENTITY_TEST_PASSWORD: $(net-identity-password)