trigger: none

extends:
  template: ../../eng/pipelines/templates/archetype-tests.yml
  parameters:
    Jobs:
    - template: jobs/archetype-sdk-tests.yml
      parameters:
        ServiceDirectory: extensions