trigger: none

extends:
  template: ../../eng/pipelines/templates/archetype-tests.yml
  parameters:
    Jobs:
    - template: jobs/archetype-sdk-tests.yml
      parameters:
        ServiceDirectory: keyvault
        EnvVars:
          # Runs samples with live tests.
          AZURE_KEYVAULT_TEST_MODE: Live
