trigger: none

extends:
  template: ../../eng/pipelines/templates/archetype-tests.yml
  parameters:
    Jobs:
    - template: jobs/archetype-sdk-tests.yml
      parameters:
        ServiceDirectory: digitaltwins
        Location: westus2
        SubscriptionConfiguration: $(sub-config-azure-cloud-test-resources-preview)
        EnvVars:
          # Runs live tests.
          AZURE_IOT_TEST_MODE: Live
